test:
	# node blsss.js -- SKIPPED: TO BE IMPLEMENTED
	node gjss.js
	node msis.js
	# node naxos.js -- SKIPPED: TO BE IMPLEMENTED
	node ois.js
	# node sigma.js -- SKIPPED: TO BE IMPLEMENTED
	node sis.js
	node sss.js